Format Correct

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,114 +3,114 @@ name: CI
 
 # Definition when the workflow should run
 on:
-  workflow_dispatch:
-  push:
-    branches:
-      - main
-    paths-ignore:
-      - "sfdx-project.json"
-      - "README.md"
+    workflow_dispatch:
+    push:
+        branches:
+            - main
+        paths-ignore:
+            - 'sfdx-project.json'
+            - 'README.md'
 
 # Jobs to be executed
 jobs:
-  format-lint-lwc-tests:
-    runs-on: ubuntu-latest
-    steps:
-      # Checkout the source code
-      - name: "Checkout source code"
-        uses: actions/checkout@v4
+    format-lint-lwc-tests:
+        runs-on: ubuntu-latest
+        steps:
+            # Checkout the source code
+            - name: 'Checkout source code'
+              uses: actions/checkout@v4
 
-      # Cache node_modules to speed up the process
-      - name: "Restore node_modules cache"
-        id: cache-npm
-        uses: actions/cache@v4
-        with:
-          path: node_modules
-          key: npm-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            npm-${{ env.cache-name }}-
-            npm-
+            # Cache node_modules to speed up the process
+            - name: 'Restore node_modules cache'
+              id: cache-npm
+              uses: actions/cache@v4
+              with:
+                  path: node_modules
+                  key: npm-${{ hashFiles('**/package-lock.json') }}
+                  restore-keys: |
+                      npm-${{ env.cache-name }}-
+                      npm-
 
-      # Install npm dependencies for Prettier and Jest
-      - name: "Install npm dependencies"
-        if: steps.cache-npm.outputs.cache-hit != 'true'
-        run: HUSKY=0 npm ci
+            # Install npm dependencies for Prettier and Jest
+            - name: 'Install npm dependencies'
+              if: steps.cache-npm.outputs.cache-hit != 'true'
+              run: HUSKY=0 npm ci
 
-      # Prettier formatting
-      #- name: "Code formatting verification with Prettier"
-      #  run: npm run prettier:verify
+            # Prettier formatting
+            - name: 'Code formatting verification with Prettier'
+              run: npm run prettier:verify
 
-      # Lint LWC / Aura
-      - name: "Lint Lightning Web Components / Aura Components"
-        run: npm run lint
+            # Lint LWC / Aura
+            - name: 'Lint Lightning Web Components / Aura Components'
+              run: npm run lint
 
-      # LWC unit tests
-      - name: "Unit test Lightning Web Components"
-        run: npm run test:unit:coverage
+            # LWC unit tests
+            - name: 'Unit test Lightning Web Components'
+              run: npm run test:unit:coverage
 
-  scratch-org-test:
-    runs-on: ubuntu-latest
-    needs: format-lint-lwc-tests
-    if: github.actor != 'dependabot[bot]'
-    steps:
-      # Checkout the source code
-      - name: "Checkout source code"
-        uses: actions/checkout@v4
+    scratch-org-test:
+        runs-on: ubuntu-latest
+        needs: format-lint-lwc-tests
+        if: github.actor != 'dependabot[bot]'
+        steps:
+            # Checkout the source code
+            - name: 'Checkout source code'
+              uses: actions/checkout@v4
 
-      # Run PMD scan
-      - name: "Run PMD scan"
-        uses: pmd/pmd-github-action@v2.0.0
-        id: pmd
-        with:
-          version: "6.55.0"
-          sourcePath: "force-app"
-          rulesets: "ruleset.xml"
+            # Run PMD scan
+            - name: 'Run PMD scan'
+              uses: pmd/pmd-github-action@v2.0.0
+              id: pmd
+              with:
+                  version: '6.55.0'
+                  sourcePath: 'force-app'
+                  rulesets: 'ruleset.xml'
 
-      # Check for PMD violations
-      - name: "Check for PMD violations"
-        if: steps.pmd.outputs.violations != 0
-        run: exit 1
+            # Check for PMD violations
+            - name: 'Check for PMD violations'
+              if: steps.pmd.outputs.violations != 0
+              run: exit 1
 
-      # Install Salesforce CLI
-      - name: "Install Salesforce CLI"
-        run: |
-          npm install @salesforce/cli --location=global
-          nodeInstallPath=$(npm config get prefix)
-          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
-          sf --version
+            # Install Salesforce CLI
+            - name: 'Install Salesforce CLI'
+              run: |
+                  npm install @salesforce/cli --location=global
+                  nodeInstallPath=$(npm config get prefix)
+                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
+                  sf --version
 
-      # Store secret for dev hub
-      - name: "Populate auth file with DEVHUB_SFDX_URL secret"
-        shell: bash
-        run: |
-          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
-          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
-          if [ $secretFileSize == 1 ]; then
-              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
-              exit 1;
-          fi
+            # Store secret for dev hub
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
 
-      # Authenticate dev hub
-      - name: "Authenticate Dev Hub"
-        run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+            # Authenticate dev hub
+            - name: 'Authenticate Dev Hub'
+              run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
-      # Create scratch org
-      - name: "Create scratch org"
-        run: sf org create scratch -f config/project-scratch-def.json -a scratch-org -d -y 1
+            # Create scratch org
+            - name: 'Create scratch org'
+              run: sf org create scratch -f config/project-scratch-def.json -a scratch-org -d -y 1
 
-      # Deploy source to scratch org
-      - name: "Push source to scratch org"
-        run: sf project deploy start -d force-app
+            # Deploy source to scratch org
+            - name: 'Push source to scratch org'
+              run: sf project deploy start -d force-app
 
-      # Assign permissionset
-      - name: "Assign permissionset to default user"
-        run: sf org assign permset -n Coral_Cloud
+            # Assign permissionset
+            - name: 'Assign permissionset to default user'
+              run: sf org assign permset -n Coral_Cloud
 
-      # Run Apex tests in scratch org
-      #- name: "Run Apex tests"
-      #  run: sf apex test run -c -r human -d ./tests/apex -w 20
+            # Run Apex tests in scratch org
+            #- name: "Run Apex tests"
+            #  run: sf apex test run -c -r human -d ./tests/apex -w 20
 
-      # Housekeeping
-      - name: "Delete scratch org"
-        if: always()
-        run: sf org delete scratch -p -o scratch-org
+            # Housekeeping
+            - name: 'Delete scratch org'
+              if: always()
+              run: sf org delete scratch -p -o scratch-org
